ALTER TABLE Categoria 
	--ADD DataInsert NOT NULL DATETIME DEFAULT GETDATE()
	ADD CONSTRAINT DF_DATAINSERT
		DEFAULT GETDATE() FOR DataInsert
GO

ALTER TABLE SubCategoria
	--ADD DataInsert NOT NULL DATETIME DEFAULT GETDATE()
	ADD CONSTRAINT DF_DATAINSERT2 
		DEFAULT GETDATE() FOR DataInsert
GO

ALTER TABLE Produto
	--ADD DataInsert NOT NULL DATETIME DEFAULT GETDATE()
	ADD CONSTRAINT DF_DATAINSERT3 
		DEFAULT GETDATE() FOR DataInsert
GO

DROP TABLE Produto
GO

Drop TABLE SubCategoria
GO

Drop TABLE Categoria
GO

CREATE TABLE CATEGORIA(
	Codigo INT NOT NULL IDENTITY(1,1),
	Descricao VARCHAR(MAX) NOT NULL,
	DataInsert DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT PK_Categoria PRIMARY KEY (Codigo)
)

CREATE TABLE SubCategoria(
	Codigo INT NOT NULL IDENTITY(1,1),
    CodigoCategoria INT NOT NULL,
    Descricao VARCHAR(MAX) NOT NULL,
    DataInsert DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_SubCategoria PRIMARY KEY (Codigo),
    CONSTRAINT FK_SubCategoria_Categoria FOREIGN KEY (CodigoCategoria) REFERENCES Categoria(Codigo)
)

CREATE TABLE Produto(
	Codigo INT NOT NULL IDENTITY(1,1),
    CodigoSubCategoria INT NOT NULL,
    CodigoCategoria INT NOT NULL,
    Descricao VARCHAR(MAX)NOT NULL,
    DataInsert DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_Produto PRIMARY KEY (Codigo),
    CONSTRAINT FK_PRODUTO_SubCategoria FOREIGN KEY (CodigoSubCategoria) REFERENCES SubCategoria (Codigo)
)
